### ISSUE TITLE
net-voip/freeswitch-1.4.18-r1: can't build gsmopen

### ISSUE THREAD

**Issue by l29ah** [alphallc/freeswitch#8]
In file included from gsmopen.h:103:0,
                 from mod_gsmopen.cpp:34:
/usr/local/include/ctb-0.16/ctb.h:10:28: fatal error: ctb-0.16/kbhit.h: No such file or directory
 #include "ctb-0.16/kbhit.h"
                            ^
compilation terminated.
make[5]: *** [mod_gsmopen_la-mod_gsmopen.lo] Error 1

**Comment by seifertm** [comment]
I have the feeling this problem is related to the number of make jobs. I also ran into it, while looking into your issue, but it no longer came up when prepending `MAKEOPTS="-j1"` to the emerge command.

I also updated the ebuild for net-libs/ctb. Maybe it did not install correctly before?

Can you give it a try and report back? Make sure you sync the overlay before you try it out.

**Comment by l29ah** [comment]
On Sun, Oct 11, 2015 at 06:18:51AM -0700, Michael Seifert wrote:
> I have the feeling this problem is related to the number of make jobs. I also ran into it, while looking into your issue, but it no longer came up when prepending `MAKEOPTS="-j1"` to the emerge command.

Same here; i guess it should be added to the ebuild.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by msva** [comment]
Adding `-j1` to ebuilds is prohibited by the Gentoo QA policy. The buildsystem should be fixed instead.

**Comment by l29ah** [comment]
∞ grep -R -- -j1 /usr/portage | wc -l
2141

I see.

**Comment by seifertm** [comment]
Closed, because FreeSWITCH 1.4 has reached its end-of-life and the corresponding ebuild was masked.
